Vault m2m
scalecube/spinless pull request #45
Opened 2020-05-27 15:27 UTC by snripa

2020-05-28 09:14 UTC, artem-v approved these changes

2020-05-28 09:14 UTC, artem-v commented on app/common/vault_api.py
> +                oidc_policy_name = f"{role}-id-token-policy"
Let's renamed this prefix `id-token-policy`  to  `oidc-token-policy`. I will update issue description.

2020-05-28 18:47 UTC, artem-v requested changes
Hold on. Don't merge. All is good with PR. But let's discuss.

2020-06-01 09:56 UTC, closed without merging

2020-06-01 09:57 UTC, snripa commented
Feature rejected